global:
  scrape_interval: 20s
  external_labels:
    monitor: "prometheus-swarm"
    
scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node_exporter'
      type: 'A'
      port: 9100
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
  - job_name: 'socat'
    dns_sd_configs:
    - names:
      - 'tasks.socat'
      type: 'A'
      port: 9323